// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC5XsmaSFuriXhpgh27t3RFvT8OMzzCz0',
    appId: '1:114509387618:web:4e29d048da7a56a07a3e3b',
    messagingSenderId: '114509387618',
    projectId: 'speedyserveapp',
    authDomain: 'speedyserveapp.firebaseapp.com',
    storageBucket: 'speedyserveapp.appspot.com',
    measurementId: 'G-BDC9P6BMR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-ADN1F_TFzPBCqFdgGEiMljJcZXFuRU',
    appId: '1:114509387618:android:0b4f41846ea8d7997a3e3b',
    messagingSenderId: '114509387618',
    projectId: 'speedyserveapp',
    storageBucket: 'speedyserveapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76MmogNFZ1yLaBFVAygtZEMoTO_O0XL0',
    appId: '1:114509387618:ios:b74fe792696e96727a3e3b',
    messagingSenderId: '114509387618',
    projectId: 'speedyserveapp',
    storageBucket: 'speedyserveapp.appspot.com',
    iosBundleId: 'com.example.speedyserveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB76MmogNFZ1yLaBFVAygtZEMoTO_O0XL0',
    appId: '1:114509387618:ios:b74fe792696e96727a3e3b',
    messagingSenderId: '114509387618',
    projectId: 'speedyserveapp',
    storageBucket: 'speedyserveapp.appspot.com',
    iosBundleId: 'com.example.speedyserveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC5XsmaSFuriXhpgh27t3RFvT8OMzzCz0',
    appId: '1:114509387618:web:4601bbab348629e77a3e3b',
    messagingSenderId: '114509387618',
    projectId: 'speedyserveapp',
    authDomain: 'speedyserveapp.firebaseapp.com',
    storageBucket: 'speedyserveapp.appspot.com',
    measurementId: 'G-FZ936X2JFW',
  );
}
